FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
WORKDIR /usr/local/app/

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -Ls https://github.com/block-core/blockcore-indexer/releases/download/#{VERSION}#/Blockcore.Indexer.Cirrus-#{VERSION}#-linux-x64.tar.gz \
    | tar -xvz -C .

EXPOSE 9910
ENTRYPOINT ["dotnet", "Blockcore.Indexer.Cirrus.dll"]
